export enum UploadErrorCode {
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',
  UNEXPECTED_FILE_FIELD = 'UNEXPECTED_FILE_FIELD',
  FILE_COUNT_EXCEEDED = 'FILE_COUNT_EXCEEDED',
  PART_COUNT_EXCEEDED = 'PART_COUNT_EXCEEDED',
  FIELD_KEY_TOO_LONG = 'FIELD_KEY_TOO_LONG',
  FIELD_VALUE_TOO_LARGE = 'FIELD_VALUE_TOO_LARGE',
  FIELD_COUNT_EXCEEDED = 'FIELD_COUNT_EXCEEDED',
  UPLOAD_ERROR = 'UPLOAD_ERROR',
  FILE_REQUIRED = 'FILE_REQUIRED',
}
