export type Media = {
  mediaCode: string;
  url: string;
};

export type ProductFormData = {
  nameVi: string;
  nameJa: string;
  description: {
    vi: string;
    ja: string;
  };
  categoryVi: string;
  categoryJa: string;
  minPriceVi: string;
  maxPriceVi: string;
  discountPercentVi: string;
  minPriceJa: string;
  maxPriceJa: string;
  discountPercentJa: string;
  cover: File | null;
  gallery: File[];
  hasVariants: boolean;
  variants: Variant[];
  error: string | null;
};

export type Variant = {
  variantId: string; // Client-side ID for React keys
  productCode: string; // Will be generated by backend, but needed for type
  attributes: {
    size: string;
  };
  originalPriceVi: string;
  discountPercentVi: string;
  originalPriceJa: string;
  discountPercentJa: string;
};
